# NUMPY

1. Numpy Arrays
2. Indexing and Selection
3. Numpy Opearations

# 14 Numpy Arrays
1. transforming python(standard) list
2. using built-in functions
3. generating random data

array attributes and functions

In [1]:
import numpy as np

## 1. transforming python(standard) list

In [2]:
mylist=[1,2,3]

In [3]:
type(mylist)

list

In [4]:
myarr=np.array(mylist)

In [5]:
myarr

array([1, 2, 3])

In [6]:
type(myarr)

numpy.ndarray

In [7]:
my_mat=[[1,2,3],[4,5,6]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6]]

In [9]:
my2arr=np.array(my_mat)

In [11]:
#2D Numpy array
my2arr

array([[1, 2, 3],
       [4, 5, 6]])

## 2. using built-in functions

In [16]:
#shift+tab
#excludes end term
a=np.arange(9,14)
a

array([ 9, 10, 11, 12, 13])

In [14]:
type(a)

numpy.ndarray

In [17]:
#step-size=2(by default its 1)
a=np.arange(9,14,2)
a

array([ 9, 11, 13])

In [18]:
#zeros array
#data-type is floating point 
#1D 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
#2D 
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
#3D 
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [21]:
#ones array
#1D
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [22]:
#2D
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
#3D
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [31]:
#linspace(linearly or evenly spaced), includes end term
#3rd parameter=number of terms you want
np.linspace(1,5,12)

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [32]:
len(np.linspace(1,5,12))

12

In [33]:
#identity matrix
#just one parameter(as identity matrix is always a square matrix)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 3. generating random data

In [34]:
#rand(uniform distribution [0,1))
#1D
np.random.rand(2)

array([0.35439259, 0.69108516])

In [37]:
#2D
np.random.rand(2,3)

array([[0.67430875, 0.49162583, 0.66036831],
       [0.02183459, 0.95726336, 0.24649567]])

In [38]:
#randn(std. normal distribution, mean=0, variance=1)
#1D
np.random.randn(3)

array([-0.35981017,  2.346092  ,  0.47288463])

In [39]:
#2D
np.random.randn(2,3)

array([[-0.52045107, -0.13076387,  0.14698898],
       [ 0.23270867,  1.16903713, -0.14812473]])

In [48]:
#randint(random integers)
#(low inclusive, high exclusive)
np.random.randint(0,10)

3

In [46]:
#3rd parameter= number of integers you want
#1D
np.random.randint(0,10,5)

array([5, 7, 9, 4, 5])

In [50]:
#3rd parameter= number of integers you want(specific shape)
#2D
np.random.randint(0,10,(5,3))

array([[0, 3, 4],
       [8, 0, 7],
       [3, 6, 7],
       [6, 8, 0],
       [6, 9, 4]])

In [51]:
#seed(gives you a particular same set everytime for same value)
#enter same seed values in the cell you want, will give same set
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [52]:
#seed=42(gives same set as above)
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [53]:
#seed=42(gives same set as above)
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

In [54]:
#seed=42(gives same set as above)
np.random.seed(42)
np.random.rand(6)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452])

In [55]:
#seed=49(gives different set as above)
np.random.seed(49)
np.random.rand(3)

array([0.30096446, 0.24706183, 0.92633514])

## array attributes and functions

In [58]:
arr=np.arange(0,25)
arr
#check shape of array
arr.shape

(25,)

In [60]:
#reshaping possible only when 25=5*5 kind off...
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
#valueError--> 25!=5*4
#arr.reshape(5,4)

In [74]:
#max min
ranarr=np.random.randint(1,100,25)
ranarr

array([76, 45, 10, 27, 24, 67, 85, 13, 42,  4, 25, 49,  7, 41, 72, 52, 14,
        9, 46,  4, 94, 44, 87, 55, 10])

In [75]:
#check maximum value
ranarr.max()

94

In [76]:
#check minimum value
ranarr.min()

4

In [77]:
#check index of maximum value
ranarr.argmax()

20

In [78]:
#check index of minimum value
ranarr.argmin()

9

In [79]:
#datatype
ranarr.dtype

dtype('int32')

In [80]:
#shape
ranarr.shape

(25,)

In [84]:
#reshaping
change=ranarr.reshape(5,5)
change

array([[76, 45, 10, 27, 24],
       [67, 85, 13, 42,  4],
       [25, 49,  7, 41, 72],
       [52, 14,  9, 46,  4],
       [94, 44, 87, 55, 10]])

In [86]:
#again check shape
change.shape

(5, 5)

# 15 Indexing and Selection
1. grabbing single element
2. Grabbing a slice of elements
3. Broadcasting selections
4. Indexing and selection in 2D
5. Conditional selection

## 1.grabbing single element

In [88]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
arr[3]

3

## 2.grabbing slice of elements

In [91]:
#excluding last term
arr[1:5]

array([1, 2, 3, 4])

In [92]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [93]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [94]:
arr[2:9:1]

array([2, 3, 4, 5, 6, 7, 8])

In [95]:
arr[2:8:2]

array([2, 4, 6])

## 3. Broadcasting Selections

In [100]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr[1:5]=100
#reflects change on actual array
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [104]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [110]:
slice_of_array=arr[0:5]
slice_of_array

array([0, 1, 2, 3, 4])

In [111]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [112]:
slice_of_array[:]=99
slice_of_array

array([99, 99, 99, 99, 99])

In [114]:
#reflects actual array
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [117]:
#what if we want not to effect broadcasting changes in original array
#explicitely set a copy--> copy()
arr_copy=arr.copy()
arr_copy[:]=101
arr_copy

array([101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])

In [118]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

## 4.Indexing and selection in 2D

In [125]:
arr2d=np.array([[1,2,3],[5,7,9],[234,43,22],[3,100,6]])
arr2d

array([[  1,   2,   3],
       [  5,   7,   9],
       [234,  43,  22],
       [  3, 100,   6]])

In [126]:
#shape=(rows, columns)
arr2d.shape

(4, 3)

In [128]:
#row 1
arr2d[1]

array([5, 7, 9])

In [131]:
arr2d[-1]

array([  3, 100,   6])

In [130]:
#element 234
arr2d[2][0]
#or
arr2d[2,0]

234

In [132]:
#slicing
arr2d[:2,1:]

array([[2, 3],
       [7, 9]])

## 5.Conditional selection

In [136]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [138]:
#condition(boolean values)
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [140]:
bool_arr=arr>4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [141]:
#only values with condition (bool_arr=True) will be extracted
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [142]:
#one step command of above
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

# 16 Numpy Operations



In [148]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
#add
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [150]:
#subtract
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [151]:
#multiply
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [154]:
#divide
arr/2
#arr/0

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [155]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
#add two arrays(datatype must be same in order to add any two things)
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [157]:
#subtract two arrays
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [158]:
#divide two arrays
arr/arr

C:\Users\ADMIN\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [159]:
#error
1/0

ZeroDivisionError: division by zero

In [160]:
#but we get result(warning) in numpy
1/arr

C:\Users\ADMIN\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [161]:
#square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [162]:
#sin()
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [163]:
#lograthmic
np.log(arr)

C:\Users\ADMIN\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [165]:
#sum of all th eelements of array
arr.sum()

45

In [166]:
#mean of all th eelements of array
arr.mean()

4.5

In [167]:
#maximum of all th eelements of array
arr.max()

9

In [168]:
#minimum of all th eelements of array
arr.min()

0

In [169]:
#variance of all th eelements of array
arr.var()

8.25

In [170]:
#std deviation of all th eelements of array
arr.std()

2.8722813232690143

In [173]:
#2D array
arr2d=np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [174]:
#shape 
arr2d.shape

(5, 5)

In [175]:
#sum of all the elements of 2d-array
arr2d.sum()

300

In [177]:
#sum across rows of the elements of 2d-array(basically its the sum of columns of a 2d array)
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [178]:
#sum across columns of the elements of 2d-array(basically its the sum of rows of a 2d array)
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])